import { Josefin_Sans } from "next/font/google";
import "./globals.css";

const josefin_font = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Jahid Hasan | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin_font.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
