import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { ThemeProviderWrapper } from "@/components/theme-provider";

const josefin_font = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Jahid Hasan | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${josefin_font.className} h-full antialiased`}
    >
      <body
        suppressHydrationWarning
        className="
          bg-gray-100
          dark:bg-linear-to-br
          dark:from-[#0B1120]
          dark:via-[#163B5E]
          dark:to-[#18163B]
          dark:bg-fixed
        "
      >
        <ThemeProviderWrapper
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-full md:w-2/3 lg:w-1/2 mx-auto px-5 md:px-0">
            <Navbar />
            {children}
          </div>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}